In [2]:
from pathlib import Path

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

In [3]:
listing_path = Path("data/mortgage/CRMLSListing_202401_202605_with_mortgage.csv")
sold_path = Path("data/mortgage/CRMLSSold_202401_202605_with_mortgage.csv")

In [4]:
listing = pd.read_csv(listing_path)
listing

/var/folders/kg/syn5dsfn40l0n2qfhr_8whqh0000gn/T/ipykernel_74412/521241561.py:1: DtypeWarning: Columns (0: ListAgentEmail) have mixed types. Specify dtype option on import or set low_memory=False.
  listing = pd.read_csv(listing_path)

,OriginalListPrice,ListingKey,ListAgentEmail,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,...,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,UnparsedAddress.1,year_month
0,1340000.0,1074973329,haleh360@Gmail.com,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,Residential,1301.0,...,177861.0,NaN,False,NaN,NaN,90067,2105.00,177861.0,2220 Avenue Of The Stars 2704,2024-01
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,Renee,Chen,33.496363,-117.691677,16 Palisades,Residential,2788.0,...,5300.0,0.0,False,3.0,Capistrano Unified,92677,254.00,5300.0,16 Palisades,2024-01
2,3150000.0,1074936537,anader@dppre.com,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,Residential,3250.0,...,9404.0,NaN,NaN,2.0,NaN,91108,NaN,9404.0,1615 Waverly Road,2024-01
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,Residential,7456.0,...,58232.0,1.0,False,4.0,Walnut Valley Unified,91765,295.95,58232.0,2250 Indian Creek Road,2024-01
4,12725000.0,1074143166,jeff.williams@pacificsir.com,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,Residential,2321.0,...,2250.0,3.0,False,2.0,Newport Mesa Unified,92662,0.00,2250.0,317 E. Bayfront,2024-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616067,849000.0,1156787989,NaN,Edward,Zamora,37.950161,-121.659890,1691 Eden Plains Rd,Residential,2222.0,...,20909.0,NaN,False,2.0,NaN,94513,NaN,20909.0,1691 Eden Plains Rd,2026-06
616068,1375000.0,1156489602,NaN,Jezer,Manalastas,32.629353,-116.949771,1561 Copper Penny Dr,Residential,3058.0,...,NaN,NaN,False,3.0,NaN,91915,125.00,NaN,1561 Copper Penny Dr,2026-06
616069,649900.0,1154722990,NaN,Benjamin,Diaz-Habben,38.114716,-122.239396,21 Monte Vista Ave,Residential,1970.0,...,7405.0,NaN,False,0.0,NaN,94590,NaN,7405.0,21 Monte Vista Ave,2026-06
616070,795000.0,1153448926,NaN,Jace,Coleman,32.837643,-116.765217,1242 Marshall Rd,Residential,1846.0,...,37897.0,NaN,False,1.0,NaN,91901,NaN,37897.0,1242 Marshall Rd,2026-06
616071,675800.0,1108634530,NaN,Sharon,Quisenberry,33.040756,-116.595224,1626 Frisius Drive,Residential,1690.0,...,28749.0,1.0,False,0.0,Julian High School,92036,0.00,28749.0,1626 Frisius Drive,2026-06

In [5]:
sold = pd.read_csv(sold_path)
sold

/var/folders/kg/syn5dsfn40l0n2qfhr_8whqh0000gn/T/ipykernel_74412/4239177719.py:1: DtypeWarning: Columns (0: ListAgentEmail, 1: BuyerAgentAOR, 2: ListAgentAOR) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv(sold_path)

,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,BuyerAgentAOR,ListAgentAOR,year_month
0,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,Joan,Wachter,...,NaN,False,1.0,Other,94401,6472.0,NaN,NaN,NaN,2024-01
1,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,Michael,Darwich,...,NaN,False,2.0,NaN,91950,NaN,NaN,NaN,NaN,2024-01
2,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,Michael,Darwich,...,NaN,False,2.0,NaN,91950,NaN,NaN,NaN,NaN,2024-01
3,NaN,True,False,2100000.0,1067652762,jenniferarielkennedy@gmail.com,2024-01-02,2100000.0,Jennifer,Kennedy,...,3.0,False,3.0,San Luis Coastal Unified,93401,0.0,11219.0,NaN,NaN,2024-01
4,Tile,True,False,1950000.0,1063453216,kira@mendosir.com,2024-01-22,1950000.0,Kira,Meade,...,NaN,NaN,2.0,NaN,95437,NaN,74487.6,NaN,NaN,2024-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447959,NaN,True,False,1388000.0,1060097689,NaN,2026-06-30,13000000.0,Reynaldo,Alvaran,...,2.0,False,1.0,Los Angeles Unified,90046,0.0,7103.0,TriCounties,TriCounties,2026-06
447960,NaN,True,True,919900.0,1037789100,NaN,2026-06-30,850000.0,Hervi,Estrada,...,1.0,False,3.0,Antelope Valley Union,93536,0.0,30228.0,Southland,Southland,2026-06
447961,"Carpet,Laminate",NaN,False,975000.0,1035814040,NaN,2026-06-11,595000.0,Phillip L.,Fair,...,NaN,False,1.0,Oakland,94608,NaN,4389.0,Oakland,Oakland,2026-06
447962,"Carpet,Laminate,Wood",True,False,649999.0,1023191564,NaN,2026-06-30,615000.0,Hervi,Estrada,...,2.0,False,2.0,Antelope Valley Union,93551,0.0,113797.0,Southland,Southland,2026-06
447963,NaN,True,False,6989995.0,1014091927,NaN,2026-06-26,3000000.0,Billie Jo,Ralls,...,3.0,False,1.0,Paso Robles Joint Unified,93461,0.0,106836562.8,NorthSanLuisObispo,NorthSanLuisObispo,2026-06

In [6]:
listing.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail',
       'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude',
       'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice',
       'DaysOnMarket', 'ListOfficeName', 'ListAgentFullName',
       'ListingKeyNumeric', 'MLSAreaMajor', 'CountyOrParish', 'PropertyType.1',
       'MlsStatus', 'ListAgentFirstName.1', 'AttachedGarageYN', 'ParkingTotal',
       'PropertySubType', 'LotSizeAcres', 'YearBuilt', 'DaysOnMarket.1',
       'StreetNumberNumeric', 'LivingArea.1', 'ListingId',
       'BathroomsTotalInteger', 'City', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ListingContractDate',
       'Latitude.1', 'ListPrice.1', 'StateOrProvince', 'FireplaceYN',
       'Stories', 'Levels', 'ListAgentLastName.1', 'LotSizeArea',
       'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces',
       'HighSchoolDistrict', 'PostalCode', 'AssociationFee',
       'LotSizeSquareFeet', 'UnparsedAddress.1', 'year_month'],
      dtype='str')

In [7]:
sold.columns

Index(['Flooring', 'ViewYN', 'PoolPrivateYN', 'OriginalListPrice',
       'ListingKey', 'ListAgentEmail', 'CloseDate', 'ClosePrice',
       'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude',
       'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice',
       'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'ListAgentFullName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'ListingKeyNumeric', 'MLSAreaMajor',
       'CountyOrParish', 'MlsStatus', 'AttachedGarageYN', 'ParkingTotal',
       'PropertySubType', 'LotSizeAcres', 'BuyerOfficeAOR', 'YearBuilt',
       'StreetNumberNumeric', 'ListingId', 'BathroomsTotalInteger', 'City',
       'BedroomsTotal', 'ContractStatusChangeDate', 'PurchaseContractDate',
       'ListingContractDate', 'StateOrProvince', 'FireplaceYN', 'Stories',
       'Levels', 'LotSizeArea', 'MainLevelBedrooms', 'NewConstructionYN',
       'GarageSpaces', 'HighSchoolDistrict', 'PostalCode', 'AssociationFee',
       'LotSizeSquareFeet', 'BuyerAgentAOR', 'ListAgentAOR', 'year_month'],
      dtype='str')

### Note on metadata fields:
- Keys: ListingKey, ListingKeyNumeric, ListingId
- Address: UnparsedAddress, StreetNumberNumeric
- Agent/list: ListAgentEmail, ListAgentFirstName, ListAgentLastName, ListAgentFullName, ListOfficeName
- Buyer-side: BuyerAgentFirstName, BuyerAgentLastName, BuyerAgentMlsId, BuyerOfficeName, BuyerOfficeAOR, BuyerAgentAOR
- Location (State): StateOrProvince

### Note on market analysis fields:
- Price: OriginalListPrice, ListPrice, ClosePrice
- Timing: CloseDate, PurchaseContractDate, ListingContractDate, DaysOnMarket, year_month
- Geography: CountyOrParish, City, PostalCode, MLSAreaMajor, HighSchoolDistrict
- Location (coordinates): Latitude, Longitude
- Property Details: PropertySubType, LivingArea, BedroomsTotal, BathroomsTotalInteger, YearBuilt, LotSizeSquareFeet, LotSizeAcres, GarageSpaces, ParkingTotal, AttachedGarageYN, Stories, Levels, MainLevelBedrooms, AssociationFee, NewConstructionYN, FireplaceYN, iewYN, PoolPrivateYN, Flooring

### Converting date columns into datetime

In [14]:
def to_datetime(df, date_columns): 

    df[date_columns] = df[date_columns].apply(pd.to_datetime, errors="coerce")

    df["year_month"] = pd.to_datetime(
        df["year_month"], format="%Y-%m", errors="coerce")
    df["Month"] = df["year_month"].dt.month
    df["Year"] = df["year_month"].dt.year

    return df

In [15]:
listing_date_columns = ["ListingContractDate", "ContractStatusChangeDate"]
sold_date_columns = date_columns = [
        "ListingContractDate",
        "PurchaseContractDate",
        "CloseDate",
        "ContractStatusChangeDate",
    ]

In [16]:
listing = to_datetime(listing, listing_date_columns)
sold = to_datetime(sold, sold_date_columns)

### Flagging date consistency violations

In [17]:
sold["listing_after_close_flag"] = sold["ListingContractDate"] > sold["CloseDate"]
sold["purchase_after_close_flag"] = sold["PurchaseContractDate"] > sold["CloseDate"]
sold["negative_timeline_flag"] = sold["ListingContractDate"] > sold["PurchaseContractDate"]

timeline_flag_columns = [
    "listing_after_close_flag",
    "purchase_after_close_flag",
    "negative_timeline_flag",
]
sold[timeline_flag_columns].sum()

listing_after_close_flag      67
purchase_after_close_flag    239
negative_timeline_flag       290
dtype: int64

### Dropping redundant list agent columns

In [18]:
def list_agent(df):
    columns = ["ListAgentEmail", "ListAgentFirstName", "ListAgentLastName"]
    df.drop(columns=columns, inplace=True)
    return df

In [19]:
listing = list_agent(listing)
sold = list_agent(sold)

### Filtering coordinates to purely California

In [24]:
def filter_coordinates(df):
    df = df.dropna(subset=["Latitude", "Longitude"])

    city_path = Path("data/city_boundaries/City_and_County_Boundaries.geojson")
    city_gdf = gpd.read_file(city_path)
    city_gdf = city_gdf.set_crs("EPSG:4326")

    california_boundary = city_gdf.dissolve()
    
    df_points = gpd.GeoDataFrame(
        df,
        geometry=gpd.points_from_xy(df["Longitude"], df["Latitude"]),
        crs="EPSG:4326",
    )

    df = (gpd.sjoin(
            df_points,
            california_boundary[["geometry"]],
            how="inner",
            predicate="within",
        )
        .drop(columns=["geometry", "index_right"])
        .pipe(pd.DataFrame)
    )

    return df

In [25]:
listing = filter_coordinates(listing)
sold = filter_coordinates(sold)

In [30]:
def filter_nono_values(df, columns):
    for column in columns:
        df = df[df[column] >= 0]
    return df

In [31]:
listing_columns = ["LivingArea", "DaysOnMarket", "BedroomsTotal", 
               "BathroomsTotalInteger"]

sold_columns = listing_columns + ["ClosePrice"]

listing = filter_nono_values(listing, listing_columns)
sold = filter_nono_values(sold, sold_columns)

In [33]:
listing

,OriginalListPrice,ListingKey,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,UnparsedAddress.1,year_month,Month,Year
0,1340000.0,1074973329,34.052207,-118.408445,2220 Avenue Of The Stars 2704,Residential,1301.0,1340000.0,127,Rodeo Realty- Brentwood,...,False,NaN,NaN,90067,2105.00,177861.0,2220 Avenue Of The Stars 2704,2024-01-01,1,2024
1,2500000.0,1074954552,33.496363,-117.691677,16 Palisades,Residential,2788.0,2500000.0,1,Your Home Sold Guaranteed Realty,...,False,3.0,Capistrano Unified,92677,254.00,5300.0,16 Palisades,2024-01-01,1,2024
2,3150000.0,1074936537,34.119345,-118.111254,1615 Waverly Road,Residential,3250.0,3150000.0,1,COMPASS,...,NaN,2.0,NaN,91108,NaN,9404.0,1615 Waverly Road,2024-01-01,1,2024
3,3090000.0,1074917818,33.984057,-117.802819,2250 Indian Creek Road,Residential,7456.0,3090000.0,0,"Signature One Realty Group, Inc",...,False,4.0,Walnut Valley Unified,91765,295.95,58232.0,2250 Indian Creek Road,2024-01-01,1,2024
4,12725000.0,1074143166,33.607583,-117.887743,317 E. Bayfront,Residential,2321.0,12725000.0,2,Pacific Sotheby's Int'l Realty,...,False,2.0,Newport Mesa Unified,92662,0.00,2250.0,317 E. Bayfront,2024-01-01,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616067,849000.0,1156787989,37.950161,-121.659890,1691 Eden Plains Rd,Residential,2222.0,849000.0,9,Zamora & Associates Inc.,...,False,2.0,NaN,94513,NaN,20909.0,1691 Eden Plains Rd,2026-06-01,6,2026
616068,1375000.0,1156489602,32.629353,-116.949771,1561 Copper Penny Dr,Residential,3058.0,1375000.0,3,Keller Williams San Diego Metro,...,False,3.0,NaN,91915,125.00,NaN,1561 Copper Penny Dr,2026-06-01,6,2026
616069,649900.0,1154722990,38.114716,-122.239396,21 Monte Vista Ave,Residential,1970.0,599888.0,24,KINGSHIP REALTY GROUP,...,False,0.0,NaN,94590,NaN,7405.0,21 Monte Vista Ave,2026-06-01,6,2026
616070,795000.0,1153448926,32.837643,-116.765217,1242 Marshall Rd,Residential,1846.0,699000.0,32,Allison James Estates & Homes,...,False,1.0,NaN,91901,NaN,37897.0,1242 Marshall Rd,2026-06-01,6,2026
616071,675800.0,1108634530,33.040756,-116.595224,1626 Frisius Drive,Residential,1690.0,675800.0,79,Coldwell Banker Country Realty,...,False,0.0,Julian High School,92036,0.00,28749.0,1626 Frisius Drive,2026-06-01,6,2026

In [32]:
sold

,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,...,AssociationFee,LotSizeSquareFeet,BuyerAgentAOR,ListAgentAOR,year_month,Month,Year,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,"Carpet,Tile,Wood",True,False,499000.0,551985747,2024-01-26,240000.0,37.566106,-122.327954,1 Baldwin Avenue 411,...,6472.0,NaN,NaN,NaN,2024-01-01,1,2024,False,False,False
1,NaN,False,False,759900.0,522107581,2024-01-05,815000.0,32.659315,-117.096922,2811 C Avenue,...,NaN,NaN,NaN,NaN,2024-01-01,1,2024,False,False,False
2,NaN,False,False,739900.0,510919001,2024-01-05,810000.0,32.659284,-117.097174,2812 C Avenue,...,NaN,NaN,NaN,NaN,2024-01-01,1,2024,False,False,False
3,NaN,True,False,2100000.0,1067652762,2024-01-02,2100000.0,35.277199,-120.646786,2054 Fixlini Street,...,0.0,11219.0,NaN,NaN,2024-01-01,1,2024,False,False,False
5,"Tile,Wood",True,NaN,NaN,1061988701,2024-01-31,2340000.0,37.325454,-121.780303,3114 Rasmus Circle,...,NaN,8712.0,NaN,NaN,2024-01-01,1,2024,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447959,NaN,True,False,1388000.0,1060097689,2026-06-30,13000000.0,34.117226,-118.372189,2525 Thames Street,...,0.0,7103.0,TriCounties,TriCounties,2026-06-01,6,2026,False,False,False
447960,NaN,True,True,919900.0,1037789100,2026-06-30,850000.0,34.635955,-118.213539,4638 W Avenue M10,...,0.0,30228.0,Southland,Southland,2026-06-01,6,2026,False,False,False
447961,"Carpet,Laminate",NaN,False,975000.0,1035814040,2026-06-11,595000.0,37.824500,-122.281570,3228 Magnolia St,...,NaN,4389.0,Oakland,Oakland,2026-06-01,6,2026,False,False,False
447962,"Carpet,Laminate,Wood",True,False,649999.0,1023191564,2026-06-30,615000.0,34.639233,-118.178343,41614 27th Street W,...,0.0,113797.0,Southland,Southland,2026-06-01,6,2026,False,False,False
447963,NaN,True,False,6989995.0,1014091927,2026-06-26,3000000.0,35.633015,-120.278054,3160 Gillis Canyon Road,...,0.0,106836562.8,NorthSanLuisObispo,NorthSanLuisObispo,2026-06-01,6,2026,False,False,False

### Dropping redundant columns
- PropertyType: Assumed to be `Residential`
- MlsStatus: Constant `Closed` value
- ListingKey: Redundant with `ListingKeyNumeric`

In [12]:
sold.drop(columns=["PropertyType", "MlsStatus", "ListingKey"], inplace=True)

In [13]:
sold.columns

Index(['Flooring', 'ViewYN', 'PoolPrivateYN', 'OriginalListPrice', 'CloseDate',
       'ClosePrice', 'Latitude', 'Longitude', 'UnparsedAddress', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'ListAgentFullName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'ListingKeyNumeric', 'MLSAreaMajor',
       'CountyOrParish', 'AttachedGarageYN', 'ParkingTotal', 'PropertySubType',
       'LotSizeAcres', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BedroomsTotal',
       'ContractStatusChangeDate', 'PurchaseContractDate',
       'ListingContractDate', 'StateOrProvince', 'FireplaceYN', 'Stories',
       'Levels', 'LotSizeArea', 'MainLevelBedrooms', 'NewConstructionYN',
       'GarageSpaces', 'HighSchoolDistrict', 'PostalCode', 'AssociationFee',
       'LotSizeSquareFeet', 'BuyerAgentAOR', 'ListAgentAOR', 'year_month',
       'Month', 'Year', 'listing_after_close_flag',
       'purchase_after_close_flag', 'negative_timeline_flag'],
      dtype='str')

### row count check:
- listing: `616072 -> 533844`
- sold: `447964 -> 443092`