In [1]:
from pathlib import Path

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
listing_path = Path("../data/cleaned/CRMLSListing_cleaned.csv")
sold_path = Path("../data/cleaned/CRMLSSold_cleaned.csv")

In [3]:
listing = pd.read_csv(listing_path, low_memory=False)
sold = pd.read_csv(sold_path, low_memory=False)

### Resolving timeline flags

The listing contract date is the MLS entry date, not the actual listing date. All CloseDate prices are valid.

Convert invalid ListingContractDate to NaT

In [4]:
listing_after_close = sold[sold["listing_after_close_flag"] == True]
listing_after_close[["ListingId", "ListingContractDate", "CloseDate"]]

          ListingId ListingContractDate   CloseDate
20      240002340SD          2024-01-31  2024-01-30
81      240002006SD          2024-01-26  2024-01-25
710     240000171SD          2024-01-02  2024-01-01
24263     224001285          2024-04-08  2024-03-29
24383   240006096SD          2024-03-21  2024-03-20
...             ...                 ...         ...
430932  260013389SD          2026-06-03  2026-06-02
447769  260018970SD          2026-08-04  2026-07-31
447789  260018783SD          2026-07-31  2026-07-16
447840  260018408SD          2026-07-28  2026-07-22
448013    226003370          2026-07-15  2026-07-10

[71 rows x 3 columns]

Original NaN count

In [5]:
sold["ListingContractDate"].isna().sum()

np.int64(1)

In [6]:
sold.loc[listing_after_close.index, "ListingContractDate"] = pd.NaT

New NaN count

In [7]:
sold["ListingContractDate"].isna().sum()

np.int64(72)

In [8]:
sold[sold["listing_after_close_flag"] == True][["ListingId", "ListingContractDate", "CloseDate"]]

          ListingId ListingContractDate   CloseDate
20      240002340SD                 NaN  2024-01-30
81      240002006SD                 NaN  2024-01-25
710     240000171SD                 NaN  2024-01-01
24263     224001285                 NaN  2024-03-29
24383   240006096SD                 NaN  2024-03-20
...             ...                 ...         ...
430932  260013389SD                 NaN  2026-06-02
447769  260018970SD                 NaN  2026-07-31
447789  260018783SD                 NaN  2026-07-16
447840  260018408SD                 NaN  2026-07-22
448013    226003370                 NaN  2026-07-10

[71 rows x 3 columns]

In [9]:
sold[sold["listing_after_close_flag"] == False][["ListingId", "ListingContractDate", "CloseDate"]]

         ListingId ListingContractDate   CloseDate
0       ML81865679          2021-10-06  2024-01-26
1        210014555          2021-03-08  2024-01-05
2        210008330          2021-03-08  2024-01-05
3       NS24001417          2023-11-15  2024-01-02
4         C1-10456          2023-11-17  2024-01-22
...            ...                 ...         ...
464809  LC24082705          2024-04-25  2026-07-21
464810  NDP2403132          2024-04-15  2026-07-29
464811  OC24046594          2024-03-06  2026-07-24
464812  OC22244329          2022-11-28  2026-07-18
464813  TR20165987          2020-08-14  2026-07-13

[464743 rows x 3 columns]